#############################################################################
# Makefile for building: HR_cat.app/Contents/MacOS/HR_cat
# Generated by qmake (3.1) (Qt 5.10.1)
# Project:  HR_cat.pro
# Template: app
# Command: /Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/bin/qmake -o Makefile HR_cat.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/local/Cellar/opencv/3.4.1_5/include/opencv -I/usr/local/Cellar/opencv/3.4.1_5/include -I/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/lib/QtGui.framework/Headers -I/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/macx-clang -F/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/lib
QMAKE         = /Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = HR_cat1.0.0
DISTDIR = /Users/yanyupeng/Documents/xmu/Graduate/QTFile/HR_cat/.tmp/HR_cat1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/lib -L/usr/local/Cellar/opencv/3.4.1_5/lib -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_dnn_objdetect -lopencv_dpm -lopencv_face -lopencv_photo -lopencv_fuzzy -lopencv_hfs -lopencv_img_hash -lopencv_line_descriptor -lopencv_optflow -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_dnn -lopencv_plot -lopencv_xfeatures2d -lopencv_shape -lopencv_video -lopencv_ml -lopencv_ximgproc -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_flann -lopencv_xobjdetect -lopencv_imgcodecs -lopencv_objdetect -lopencv_xphoto -lopencv_imgproc -lopencv_core -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		cat.cpp moc_cat.cpp
OBJECTS       = main.o \
		cat.o \
		moc_cat.o
DIST          = /Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/spec_pre.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/qdevice.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/device_config.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/common/unix.conf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/common/mac.conf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/common/macx.conf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/common/sanitize.conf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/common/gcc-base.conf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/common/clang.conf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/common/clang-mac.conf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/qconfig.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/qt_functions.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/qt_config.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/toolchain.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/default_pre.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/resolve_config.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/default_post.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/link_pkgconfig.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/qml_debug.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/mac.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/warn_on.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/qt.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/resources.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/moc.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/uic.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/unix/thread.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/qmake_use.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/file_copies.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/rez.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/exceptions.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/yacc.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/lex.prf \
		HR_cat.pro cat.h main.cpp \
		cat.cpp
QMAKE_TARGET  = HR_cat
DESTDIR       = 
TARGET        = HR_cat.app/Contents/MacOS/HR_cat

####### Custom Variables
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET): ui_cat.h $(OBJECTS)  
	@test -d HR_cat.app/Contents/MacOS/ || mkdir -p HR_cat.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: HR_cat.pro /Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/macx-clang/qmake.conf /Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/spec_pre.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/qdevice.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/device_config.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/common/unix.conf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/common/mac.conf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/common/macx.conf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/common/sanitize.conf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/common/gcc-base.conf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/common/clang.conf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/common/clang-mac.conf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/qconfig.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_location.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/qt_functions.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/qt_config.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/macx-clang/qmake.conf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/spec_post.prf \
		../.qmake.stash \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/exclusive_builds.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/sdk.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/toolchain.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/toolchain.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/default_pre.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/default_pre.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/resolve_config.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/default_post.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/default_post.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/objective_c.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/link_pkgconfig.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/qml_debug.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/mac.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/warn_on.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/qt.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/resources.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/moc.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/unix/opengl.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/uic.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/unix/thread.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/qmake_use.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/file_copies.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/rez.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/testcase_targets.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/exceptions.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/yacc.prf \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/lex.prf \
		HR_cat.pro \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile HR_cat.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/spec_pre.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/qdevice.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/device_config.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/common/unix.conf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/common/mac.conf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/common/macx.conf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/common/sanitize.conf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/common/gcc-base.conf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/common/gcc-base-mac.conf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/common/clang.conf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/common/clang-mac.conf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/qconfig.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_charts.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_core.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_help.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_location.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_network.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_repparser.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_script.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_script_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webengine.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webview.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/qt_functions.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/qt_config.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/macx-clang/qmake.conf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/spec_post.prf:
../.qmake.stash:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/exclusive_builds.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/sdk.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/toolchain.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/toolchain.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/default_pre.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/default_pre.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/resolve_config.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/default_post.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/default_post.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/objective_c.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/link_pkgconfig.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/qml_debug.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/mac.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/warn_on.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/qt.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/resources.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/moc.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/unix/opengl.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/uic.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/unix/thread.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/qmake_use.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/file_copies.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/rez.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/testcase_targets.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/exceptions.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/yacc.prf:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/lex.prf:
HR_cat.pro:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile HR_cat.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

HR_cat.app/Contents/PkgInfo: 
	@test -d HR_cat.app/Contents || mkdir -p HR_cat.app/Contents
	@$(DEL_FILE) HR_cat.app/Contents/PkgInfo
	@echo "APPL????" > HR_cat.app/Contents/PkgInfo
HR_cat.app/Contents/Resources/empty.lproj: 
	@test -d HR_cat.app/Contents/Resources || mkdir -p HR_cat.app/Contents/Resources
	@touch HR_cat.app/Contents/Resources/empty.lproj
	
HR_cat.app/Contents/Info.plist: 
	@test -d HR_cat.app/Contents || mkdir -p HR_cat.app/Contents
	@$(DEL_FILE) HR_cat.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.HR-cat,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.HR-cat,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.10,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,HR_cat,g" -e "s,@LIBRARY@,HR_cat,g" -e "s,\$${EXECUTABLE_NAME},HR_cat,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/macx-clang/Info.plist.app >HR_cat.app/Contents/Info.plist

all: Makefile \
		HR_cat.app/Contents/PkgInfo \
		HR_cat.app/Contents/Resources/empty.lproj \
		HR_cat.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents cat.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp cat.cpp $(DISTDIR)/
	$(COPY_FILE) --parents cat.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r HR_cat.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -dM -E -o moc_predefs.h /Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_cat.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_cat.cpp
moc_cat.cpp: /Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		cat.h \
		moc_predefs.h \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/bin/moc
	/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/mkspecs/macx-clang -I/Users/yanyupeng/Documents/xmu/Graduate/QTFile/HR_cat -I/usr/local/Cellar/opencv/3.4.1_5/include/opencv -I/usr/local/Cellar/opencv/3.4.1_5/include -I/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers -I/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/lib/QtGui.framework/Headers -I/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/9.1.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk/usr/include -F/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/lib cat.h -o moc_cat.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_cat.h
compiler_uic_clean:
	-$(DEL_FILE) ui_cat.h
ui_cat.h: cat.ui \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/bin/uic
	/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/bin/uic cat.ui -o ui_cat.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp cat.h \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

cat.o: cat.cpp cat.h \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		/Users/yanyupeng/Qt5.10.1/5.10.1/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_cat.h \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/core.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/cvdef.h \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/hal/interface.h \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/cv_cpu_dispatch.h \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/cv_cpu_helper.h \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/version.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/base.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/opencv_modules.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/cvstd.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/ptr.inl.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/neon_utils.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/vsx_utils.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/traits.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/matx.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/saturate.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/fast_math.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/types.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/mat.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/bufferpool.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/mat.inl.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/persistence.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/operations.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/cvstd.inl.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/utility.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/core_c.h \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/types_c.h \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/optim.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/core/ovx.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/highgui/highgui.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/highgui.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/imgcodecs.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/videoio.hpp \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/highgui/highgui_c.h \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/imgproc/imgproc_c.h \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/imgproc/types_c.h \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/imgcodecs/imgcodecs_c.h \
		/usr/local/Cellar/opencv/3.4.1_5/include/opencv2/videoio/videoio_c.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cat.o cat.cpp

moc_cat.o: moc_cat.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cat.o moc_cat.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

